epochs: 100
batch_size: 64
patience: 10
milestone_step: 4
gamma: 0.5
lr: 0.001
dataset: '2016.10a'

num_classes: 11
num_level: 1
regu_details: 0.01
regu_approx: 0.01
kernel_size: 3
in_channels: 64
latent_dim: 320

monitor: 'acc'
test_batch_size: 128
initial_dropout_rate: 0.3
max_dropout_rate: 0.6
dropout_threshold: 0.001
acc_threshold: 0.01
patience_acc_diff: 4

